# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/text_into_commands.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/text_into_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/text_into_commands.proto\x12\x10text_to_commands\"%\n\x15TextToCommandsRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"*\n\x16TextToCommandsResponse\x12\x10\n\x08\x63ommands\x18\x01 \x03(\t2~\n\x0eTextToCommands\x12l\n\x15\x43onvertTextToCommands\x12\'.text_to_commands.TextToCommandsRequest\x1a(.text_to_commands.TextToCommandsResponse\"\x00\x42;\n\x1c\x63om.example.text_to_commandsB\x13TextToCommandsProtoP\x01\xa2\x02\x03TTCb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.text_into_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.example.text_to_commandsB\023TextToCommandsProtoP\001\242\002\003TTC'
  _globals['_TEXTTOCOMMANDSREQUEST']._serialized_start=53
  _globals['_TEXTTOCOMMANDSREQUEST']._serialized_end=90
  _globals['_TEXTTOCOMMANDSRESPONSE']._serialized_start=92
  _globals['_TEXTTOCOMMANDSRESPONSE']._serialized_end=134
  _globals['_TEXTTOCOMMANDS']._serialized_start=136
  _globals['_TEXTTOCOMMANDS']._serialized_end=262
# @@protoc_insertion_point(module_scope)
