FROM node:14-alpine
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Then copy the rest of the application
COPY . .
# ADD ../protos ./protos/

CMD ["/bin/sh"]